import { browser } from 'wxt/browser';
import * as pdfjs from 'pdfjs-dist';
import pdfWorkerUrl from 'pdfjs-dist/build/pdf.worker.mjs?url';
import '../../src/ui/standalone.css';
import { splitSubtitleText, translatePlainText, translateTextPieces } from '../../src/core/plain-text';
import { LANGUAGES } from '../../src/shared/constants';
import { errorMessage } from '../../src/shared/errors';
import type { RuntimeMessage, Settings } from '../../src/shared/types';

pdfjs.GlobalWorkerOptions.workerSrc = pdfWorkerUrl;
const provider=document.querySelector<HTMLSelectElement>('#provider')!,source=document.querySelector<HTMLSelectElement>('#source-language')!,target=document.querySelector<HTMLSelectElement>('#target-language')!;
const fileInput=document.querySelector<HTMLInputElement>('#file-input')!,dropZone=document.querySelector<HTMLDivElement>('#drop-zone')!,fileInfo=document.querySelector<HTMLDivElement>('#file-info')!,previewGrid=document.querySelector<HTMLDivElement>('#preview-grid')!,actions=document.querySelector<HTMLDivElement>('#document-actions')!;
const sourcePreview=document.querySelector<HTMLDivElement>('#source-preview')!,targetPreview=document.querySelector<HTMLDivElement>('#target-preview')!,status=document.querySelector<HTMLDivElement>('#status')!,translateButton=document.querySelector<HTMLButtonElement>('#translate')!,downloadButton=document.querySelector<HTMLButtonElement>('#download')!;
let settings:Settings,currentFile:File|undefined,sourceText='',translatedText='';
function setStatus(text:string,type:'normal'|'success'|'error'='normal'):void{status.textContent=text;status.className=`status-line${type==='normal'?'':` ${type}`}`;}
function fillLanguages(select:HTMLSelectElement,includeAuto:boolean):void{LANGUAGES.forEach(([value,label])=>{if(includeAuto||value!=='auto')select.add(new Option(label,value));});}
function fillProviders():void{const free=document.createElement('optgroup');free.label='免费组';free.append(new Option('Microsoft Translate','microsoft'),new Option('Google Translate','google'));provider.append(free);const enabled=settings.customProviders.filter(item=>item.enabled);if(enabled.length){const group=document.createElement('optgroup');group.label='自定义组';enabled.forEach(item=>group.append(new Option(item.name,`custom:${item.id}`)));provider.append(group);}provider.value=settings.providerId;}
async function extractPdf(file:File):Promise<string>{const data=new Uint8Array(await file.arrayBuffer());const document=await pdfjs.getDocument({data}).promise;const pages:string[]=[];for(let pageNumber=1;pageNumber<=document.numPages;pageNumber+=1){setStatus(`正在解析 PDF ${pageNumber}/${document.numPages}…`);const page=await document.getPage(pageNumber);const content=await page.getTextContent();let text='';for(const item of content.items){if('str' in item){text+=item.str;if('hasEOL' in item&&item.hasEOL)text+='\n';else text+=' ';}}pages.push(`--- 第 ${pageNumber} 页 ---\n${text.replace(/[ \t]+\n/g,'\n').replace(/ {2,}/g,' ').trim()}`);}return pages.join('\n\n');}
async function readFile(file:File):Promise<string>{const ext=file.name.split('.').pop()?.toLowerCase();if(ext==='pdf'||file.type==='application/pdf')return await extractPdf(file);const raw=await file.text();if(ext==='html'||ext==='htm'||file.type==='text/html'){const doc=new DOMParser().parseFromString(raw,'text/html');return doc.body.innerText;}return raw;}
async function loadFile(file:File):Promise<void>{currentFile=file;translatedText='';downloadButton.disabled=true;translateButton.disabled=true;targetPreview.textContent='';try{sourceText=await readFile(file);if(!sourceText.trim())throw new Error('没有从文档中读取到文本');sourcePreview.textContent=sourceText;document.querySelector('#file-name')!.textContent=file.name;document.querySelector('#file-size')!.textContent=`${(file.size/1024).toFixed(1)} KB · ${sourceText.length} 个字符`;document.querySelector('#file-badge')!.textContent=(file.name.split('.').pop()||'FILE').toUpperCase();fileInfo.classList.add('visible');previewGrid.classList.add('visible');actions.classList.add('visible');dropZone.style.display='none';translateButton.disabled=false;setStatus('文档解析完成，可以开始翻译','success');}catch(error){setStatus(errorMessage(error),'error');currentFile=undefined;}}
async function saveSelections():Promise<void>{settings={...settings,providerId:provider.value as Settings['providerId'],sourceLanguage:source.value,targetLanguage:target.value};settings=await browser.runtime.sendMessage({type:'SAVE_SETTINGS',settings} satisfies RuntimeMessage) as Settings;}
async function initialize():Promise<void>{fillLanguages(source,true);fillLanguages(target,false);settings=await browser.runtime.sendMessage({type:'GET_SETTINGS'} satisfies RuntimeMessage) as Settings;fillProviders();source.value=settings.sourceLanguage;target.value=settings.targetLanguage;}
fileInput.addEventListener('change',()=>{const file=fileInput.files?.[0];if(file)void loadFile(file);});document.querySelector('#choose')!.addEventListener('click',()=>fileInput.click());
for(const type of ['dragenter','dragover'])dropZone.addEventListener(type,event=>{event.preventDefault();dropZone.classList.add('dragging');});for(const type of ['dragleave','drop'])dropZone.addEventListener(type,event=>{event.preventDefault();dropZone.classList.remove('dragging');});dropZone.addEventListener('drop',event=>{const file=event.dataTransfer?.files[0];if(file)void loadFile(file);});dropZone.addEventListener('click',()=>fileInput.click());
document.querySelector('#remove')!.addEventListener('click',()=>{currentFile=undefined;sourceText='';translatedText='';fileInput.value='';fileInfo.classList.remove('visible');previewGrid.classList.remove('visible');actions.classList.remove('visible');dropZone.style.display='grid';setStatus('支持 PDF、TXT、Markdown、HTML、SRT 和 VTT');});
translateButton.addEventListener('click',async()=>{if(!currentFile||!sourceText)return;translateButton.disabled=true;downloadButton.disabled=true;targetPreview.textContent='';try{await saveSelections();const ext=currentFile.name.split('.').pop()?.toLowerCase();const progress=(value:{completed:number;total:number})=>setStatus(`正在翻译 ${value.completed}/${value.total}…`);translatedText=ext==='srt'||ext==='vtt'?await translateTextPieces(splitSubtitleText(sourceText),settings,progress,'subtitle',{title:currentFile.name}):await translatePlainText(sourceText,settings,progress,'document',{title:currentFile.name});targetPreview.textContent=translatedText;downloadButton.disabled=false;setStatus('文档翻译完成','success');}catch(error){setStatus(errorMessage(error),'error');}finally{translateButton.disabled=false;}});
downloadButton.addEventListener('click',()=>{if(!currentFile||!translatedText)return;const ext=currentFile.name.split('.').pop()?.toLowerCase()||'txt';const outputExt=ext==='pdf'||ext==='html'||ext==='htm'?'txt':ext;const base=currentFile.name.replace(/\.[^.]+$/,'');const url=URL.createObjectURL(new Blob([translatedText],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`${base}.translated.${outputExt}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
document.querySelector('#open-options')!.addEventListener('click',()=>void browser.runtime.openOptionsPage());document.querySelector('#open-text')!.addEventListener('click',()=>void browser.tabs.create({url:browser.runtime.getURL('/text-translate.html')}));
void initialize().catch(error=>setStatus(errorMessage(error),'error'));
